CREATE TABLE IF NOT EXISTS twin_cage_status_violation (
  id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
  rule_id             BIGINT        NOT NULL COMMENT '关联 twin_violation_rule.id',
  scan_batch_id       VARCHAR(64)   COMMENT '触发时的同步批次ID',
  status_code         VARCHAR(32)   COMMENT '触发的特殊状态类型',
  cage_shelve_id      BIGINT        COMMENT '笼架ID',
  position_x          INT           COMMENT '笼位X坐标',
  position_y          INT           COMMENT '笼位Y坐标',
  position_label      VARCHAR(16)   COMMENT '笼位标签如 A-3',
  cage_box_qr_code    VARCHAR(512)  COMMENT '笼盒卡号',
  project_pi_name     VARCHAR(128)  COMMENT '课题组PI',
  project_group_name  VARCHAR(256)  COMMENT '课题组名称',
  department_name     VARCHAR(256)  COMMENT '部门',
  room_name           VARCHAR(128)  COMMENT '房间名称',
  campus_name         VARCHAR(64)   COMMENT '园区名称',
  triggered_at        DATETIME      COMMENT '触发时间',
  status              VARCHAR(20)   DEFAULT 'ACTIVE' COMMENT 'ACTIVE / CLEARED / EXPIRED',
  created_at          DATETIME      DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rule (rule_id),
  INDEX idx_batch (scan_batch_id),
  INDEX idx_status (status),
  INDEX idx_group (project_group_name(64))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笼架特殊状态违规父记录';
