CREATE TABLE IF NOT EXISTS agv_coord_config (
    robot_ip     VARCHAR(20) PRIMARY KEY COMMENT '机器人IP',
    rotation_deg DOUBLE NOT NULL DEFAULT 0 COMMENT '坐标系旋转角度(度)',
    updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AGV坐标系旋转配置';
