CREATE TABLE IF NOT EXISTS student_cage_shelf_snapshot (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    snapshot_batch_id VARCHAR(64) NOT NULL,
    shelve_id VARCHAR(64) NOT NULL,
    room_id BIGINT,
    room_name VARCHAR(128),
    campus_name VARCHAR(64),
    area_name VARCHAR(64),
    floor_name VARCHAR(64),
    shelve_name VARCHAR(128),
    position_x INT,
    position_y INT,
    position_label VARCHAR(16),
    animal_cage_type INT,
    state_label VARCHAR(64),
    project_pi_name VARCHAR(128),
    department_name VARCHAR(128),
    cage_box_qr_code VARCHAR(128),
    aup_number VARCHAR(128),
    is_empty BOOLEAN DEFAULT TRUE,
    raw_data_json TEXT,
    refreshed_at DATETIME,
    refreshed_by VARCHAR(64),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_batch (snapshot_batch_id),
    INDEX idx_shelve (shelve_id),
    INDEX idx_department (department_name),
    INDEX idx_project_pi (project_pi_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
